repos:
  - repo: local
    hooks:
      - id: check-json
        name: "âœ… Check JSON files"
        language: system
        types: [json]
        entry: poetry run check-json
      - id: check-toml
        name: "âœ… Check TOML files"
        language: system
        types: [toml]
        entry: poetry run check-toml
      - id: check-yaml
        name: "âœ… Check YAML files"
        language: system
        types: [yaml]
        entry: poetry run check-yaml
      - id: check-json
        name: "ğŸ“ Check for large files"
        language: system
        entry: poetry run check-added-large-files
      - id: check-json
        name: "ğŸ› Check for forgotten debug statemens"
        language: system
        types: [python]
        entry: poetry run debug-statement-hook
      - id: check-merge-conflict
        name: "ğŸ’¥ Check for merge conflicts"
        language: system
        types: [text]
        entry: poetry run check-merge-conflict
      - id: check-symlinks
        name: "ğŸ”— Check for broken symlinks"
        language: system
        types: [symlink]
        entry: poetry run check-symlinks
      - id: codespell
        name: "ğŸ’­ Check for code spelling"
        entry: poetry run codespell --write-changes --skip="./*"
        language: system
        pass_filenames: false
        always_run: true
      - id: end-of-file-fixer
        name: "ğŸ”š Fix End of Files"
        language: system
        types: [text]
        entry: poetry run end-of-file-fixer
        stages: [commit, push, manual]
      - id: end-of-file-fixer
        name: "â¬œ Fix trailing whitespaces"
        language: system
        types: [text]
        entry: poetry run end-of-file-fixer
        stages: [commit, push, manual]
      - id: ruff-check
        name: "ğŸ¶ Ruff Linter"
        language: system
        types: [python]
        entry: poetry run ruff check --fix
        require_serial: true
        stages: [commit, push, manual]
      - id: ruff-format
        name: "ğŸ¶ Ruff Formatter"
        language: system
        types: [python]
        entry: poetry run ruff format
        require_serial: true
        stages: [commit, push, manual]
      - id: poetry pyproject check
        name: "ğŸ“œ Check pyproject with Poetry"
        language: system
        entry: poetry check
        pass_filenames: false
        always_run: true
      - id: no-commit-to-branch
        name: "ğŸ›‘ Don't commit to main branch"
        language: system
        entry: poetry run no-commit-to-branch
        pass_filenames: false
        always_run: true
        args:
          - --branch=master
          - --branch=main
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: ğŸ¨ Format using prettier
