[tool.poetry]
name = "toyota"
version = "0.0.0"
description = "Toyota Connected Services integration for Home Assistant"
authors = ["DurgNomis-drol <simongrud@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
homeassistant = ">=2022.6"
mytoyota = "0.9.1"
arrow = "^1.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.11.1"
black = "^22.3"
flake8 = "^3.8.4"
pylint = "^2.7.2"
isort = "^5.7.0"

[tool.pylint.messages_control]
# Reasons disabled:
# too-many-* - not enforced for the sake of readability
# too-few-* - same as too-many-*
disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
]

[tool.pylint.format]
max-line-length = 88

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
known_first_party = [
    "homeassistant",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
