[tool.poetry]
name = "toyota"
version = "0.0.0"
description = "Toyota Connected Services integration for Home Assistant"
authors = ["DurgNomis-drol <simongrud@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
homeassistant = ">=2022.6"
mytoyota = "^0.9.1"
arrow = "^1.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.11.1"
black = "^22.12.0"
ruff = "^0.0.246"

[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    "YTT",
    # Isort
    "I001",
    "I002"
]
line-length = 88
fix = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
