---
name: "Linting"

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit"
    strategy:
      matrix:
        python-version: [3.11]
    runs-on: "ubuntu-latest"
    steps:
      - name: "â¤µï¸ Check out code from GitHub"
        uses: "actions/checkout@v4"
      - name: "ğŸ Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "âš™ï¸ Install Poetry"
        uses: "abatilo/actions-poetry@v2.3.0"
      - name: "âš™ï¸ Install dependencies"
        run: "poetry install"
      - name: "ğŸš€ Run pre-commit on all files"
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files --show-diff-on-failure --color=always
