name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_pytest:
    name: Run tests
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
      - name: "â¤µï¸ Check out code from GitHub"
        uses: actions/checkout@v2
      - name: "âš™ï¸ Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "âš™ï¸ Set up Poetry"
        uses: abatilo/actions-poetry@v2.3.0
      - name: "âš™ï¸ Create venv"
        run: python3.9 -m venv test_env
      - name: "âš™ï¸ Switch to venv"
        run: source test_env/bin/activate
      - name: "âš™ï¸ Install dependencies"
        run: poetry install
      - name: "ğŸš€ Run all tests"
        run: -m pytest tests -v
