---
name: "Release"

on:
  release:
    types: ["published"]

jobs:
  release_zip_file:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "â¤µï¸ Check out code from GitHub"
        uses: "actions/checkout@v4"
      - name: "âš™ï¸ Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"
      - name: "âš™ï¸ Set version number"
        run: |
          "python .github/scripts/update_manifest.py --version ${{ steps.version.outputs.version }}"
      - name: "ğŸ“¦ Create zip"
        run: |
          cd custom_components/toyota
          zip toyota.zip -r ./
      - name: "â¬†ï¸ Upload zip to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./custom_components/toyota/toyota.zip"
          asset_name: "toyota.zip"
          tag: "${{ github.ref }}"
          overwrite: true
